# Generated by Django 3.2.2 on 2021-05-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('tagline', models.CharField(default='', max_length=100, verbose_name='Тег')),
                ('description', models.TextField(verbose_name='Опис')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(default=2019, verbose_name='Дата виходу')),
                ('country', models.CharField(max_length=30, verbose_name='Країна')),
                ('budget', models.PositiveIntegerField(default=0, help_text='вказувати суму в доларах', verbose_name='Бюджет')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, help_text='Вказувати суму в доларах', verbose_name='Збори в США')),
                ('fees_in_world', models.PositiveIntegerField(default=0, help_text='Вказувати суму в доларах', verbose_name='Збори в Світі')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Чорновик')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
            },
        ),
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel/', verbose_name='Зображення фото туру')),
                ('title', models.CharField(max_length=200, verbose_name='Заговолок')),
                ('uan', models.CharField(max_length=5, verbose_name='Ціна')),
                ('eat', models.CharField(max_length=200, verbose_name='Харчування')),
                ('day', models.CharField(max_length=200, verbose_name='Кількість днів')),
                ('video', models.CharField(max_length=300, verbose_name='Ссилка на відео')),
                ('description', models.TextField(verbose_name='Програма туру')),
                ('image1', models.ImageField(upload_to='travel/', verbose_name='Додаткове фото 1')),
                ('image2', models.ImageField(upload_to='travel/', verbose_name='Додаткове фото 2')),
                ('image3', models.ImageField(upload_to='travel/', verbose_name='Додаткове фото 3')),
                ('image4', models.ImageField(upload_to='travel/', verbose_name='Додаткове фото 4')),
                ('descriptione', models.TextField(verbose_name='Опис проживання 2')),
                ('image5', models.ImageField(upload_to='travel/', verbose_name='Фото проживання 1')),
                ('image6', models.ImageField(upload_to='travel/', verbose_name='Фото проживання 2')),
                ('image7', models.ImageField(upload_to='travel/', verbose_name='Фото проживання 3')),
                ('image8', models.ImageField(upload_to='travel/', verbose_name='Фото проживання 4')),
                ('descriptions', models.TextField(verbose_name='У вартість входить: ')),
                ('date', models.CharField(max_length=200, verbose_name='Дати виїздів')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Автобусний тур нові',
                'verbose_name_plural': 'Автобусні нові',
            },
        ),
    ]
