# Generated by Django 3.2.2 on 2021-05-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotravel', '0002_newslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsList',
        ),
    ]
