# Generated by Django 3.2.2 on 2021-05-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Імя')),
                ('image', models.ImageField(upload_to='logo/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотипи',
            },
        ),
    ]
