# Generated by Django 3.2.2 on 2021-05-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
