# Generated by Django 3.2.2 on 2021-05-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Імя')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Зображення')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='id')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
    ]
