# Generated by Django 3.2.2 on 2021-05-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AlterField(
            model_name='logos',
            name='image',
            field=models.ImageField(upload_to='logo/', verbose_name='Зображення Лого'),
        ),
        migrations.AlterField(
            model_name='logos',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Імя Лого'),
        ),
    ]
