# Generated by Django 3.2.2 on 2021-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210510_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заговолок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('descriptions', models.TextField(verbose_name='Короткий опис')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Зображення новини')),
                ('image1', models.ImageField(upload_to='news/', verbose_name='Додаткове фото 1')),
                ('image2', models.ImageField(upload_to='news/', verbose_name='Додаткове фото 2')),
                ('image3', models.ImageField(upload_to='news/', verbose_name='Додаткове фото 3')),
                ('image4', models.ImageField(upload_to='news/', verbose_name='Додаткове фото 4')),
            ],
            options={
                'verbose_name': 'Новини',
                'verbose_name_plural': 'Новини',
            },
        ),
    ]
