# Generated by Django 3.2.2 on 2021-05-11 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Зображення новини')),
                ('title', models.CharField(max_length=200, verbose_name='Заговолок')),
                ('descriptions', models.TextField(verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис 1')),
                ('image1', models.ImageField(upload_to='news/', verbose_name='Додаткове фото 1')),
                ('image2', models.ImageField(upload_to='news/', verbose_name='Додаткове фото 2')),
                ('image3', models.ImageField(upload_to='news/', verbose_name='Додаткове фото 3')),
                ('image4', models.ImageField(upload_to='news/', verbose_name='Додаткове фото 4')),
                ('descriptione', models.TextField(verbose_name='Опис 2')),
                ('date', models.DateField(default=datetime.date(2021, 5, 11))),
            ],
            options={
                'verbose_name': 'Новини',
                'verbose_name_plural': 'Новини',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'НовиниDelate', 'verbose_name_plural': 'НовиниDelate'},
        ),
    ]
