# Generated by Django 3.2.2 on 2021-05-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='url',
            field=models.SlugField(default=2, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
