# Generated by Django 3.2.2 on 2021-05-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210512_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travels',
            options={'verbose_name': 'Автобусний', 'verbose_name_plural': 'Автобусні'},
        ),
    ]
