# Generated by Django 3.2.2 on 2021-05-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_travels_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels',
            name='url',
        ),
    ]
