# Generated by Django 3.2.2 on 2021-05-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_travels_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels',
            name='date',
        ),
    ]
