# Generated by Django 3.2.2 on 2021-05-12 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_travels_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel/', verbose_name='Зображення фото туру')),
                ('title', models.CharField(max_length=200, verbose_name='Заговолок')),
                ('date', models.DateField(default=datetime.date(2021, 5, 12))),
                ('uan', models.CharField(max_length=5, verbose_name='Ціна')),
                ('eat', models.CharField(max_length=200, verbose_name='Харчування')),
                ('day', models.CharField(max_length=200, verbose_name='Кількість днів')),
                ('video', models.CharField(max_length=300, verbose_name='Ссилка на відео')),
                ('description', models.TextField(verbose_name='Програма туру')),
                ('image1', models.ImageField(upload_to='travel/', verbose_name='Додаткове фото 1')),
                ('image2', models.ImageField(upload_to='travel/', verbose_name='Додаткове фото 2')),
                ('image3', models.ImageField(upload_to='travel/', verbose_name='Додаткове фото 3')),
                ('image4', models.ImageField(upload_to='travel/', verbose_name='Додаткове фото 4')),
                ('descriptione', models.TextField(verbose_name='Опис проживання 2')),
                ('image5', models.ImageField(upload_to='travel/', verbose_name='Фото проживання 1')),
                ('image6', models.ImageField(upload_to='travel/', verbose_name='Фото проживання 2')),
                ('image7', models.ImageField(upload_to='travel/', verbose_name='Фото проживання 3')),
                ('image8', models.ImageField(upload_to='travel/', verbose_name='Фото проживання 4')),
                ('descriptions', models.TextField(verbose_name='У вартість входить: ')),
            ],
            options={
                'verbose_name': 'Автобусний',
                'verbose_name_plural': 'Автобусні',
            },
        ),
        migrations.DeleteModel(
            name='Travels',
        ),
    ]
