# Generated by Django 3.2.2 on 2021-05-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210512_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='date',
        ),
    ]
