# Generated by Django 3.2.2 on 2021-05-12 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 12)),
        ),
    ]
