# Generated by Django 3.2.2 on 2021-05-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_travel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='date',
        ),
    ]
