# Generated by Django 3.2.2 on 2021-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='date',
            field=models.CharField(default=2, max_length=200, verbose_name='Дати виїздів:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='url',
            field=models.SlugField(default=2, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
