# Generated by Django 3.2.2 on 2021-05-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_movie_world_premiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='url',
        ),
    ]
