# Generated by Django 3.2.2 on 2021-05-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210512_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Автобусний тур', 'verbose_name_plural': 'Автобусні тури'},
        ),
    ]
