# Generated by Django 3.2.2 on 2021-05-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210512_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
