# Generated by Django 3.2.2 on 2021-05-17 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_delete_travel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travels',
        ),
        migrations.AlterField(
            model_name='newslist',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
    ]
