# Generated by Django 3.2.2 on 2021-08-14 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210517_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 14)),
        ),
    ]
